# Generated by Django 3.1.5 on 2021-03-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_auto_20210303_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
